# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OpenSource Advent Challenge 2016
description: > # this means to ignore newlines until "baseurl:"
  Damians Open Source Advents Challenge 2016
baseurl: "/opensource-advent-challenge-2016" # the subpath of your site, e.g. /blog
url: "https://puzzle.github.io" # the base hostname & protocol for your site
twitter_username: puzzleitc
github_username:  puzzle

# Build settings
markdown: kramdown

collections:
- doors
